In [1]:
import pandas as pd
patent_listed_id=pd.read_csv('data\patent_co_stk_listed_1968_5k_202408.csv',index_col=0)
patent_co_stk_list=pd.read_csv('data\patent_co_stk_list_1983_6k_202408_last.csv',index_col=0)

patent_co=patent_co_stk_list.merge(patent_listed_id,on= ['公开（公告）号', '申请人', '申请号', '申请日'],how='left')
patent_co.drop_duplicates(subset=['股票代码','申请号','公开（公告）号'],inplace=True)
patent_co.申请日=pd.to_datetime(patent_co_stk_list.申请日)
patent_co.sort_values(by=['申请日','股票代码'],inplace=True)
patent_co.shape#1985628

(1985628, 36)

In [2]:
del patent_listed_id
del patent_co_stk_list

In [5]:
patent_co.股票代码.isna().sum()

2

In [6]:
patent_co[patent_co.股票代码.isna()]

,序号,标题 (中文),摘要 (中文),申请人,申请日,申请号,首次公开日,公开（公告）号,专利类型,专利有效性,...,许可次数,转让次数,权利要求数量,当前法律状态,公开类型,table_name,工商全称,中文全称,股票代码,首次上市日期
713278,1284116,一种制备橙花醇/香叶醇的方法,本发明公开了一种制备橙花醇/香叶醇的方法，该方法使用Pt@C催化剂进行非均相催化，将橙花醛/...,万华化学集团股份有限公司,2019-12-10,CN201911274019.4,2021-06-18,CN112979422B,发明授权,有效,...,NaN,1.0,18.0,授权,发明授权,patent202404,万华化学集团股份有限公司,NaN,NaN,NaN
712817,1284122,一种制备橙花醇/香叶醇的方法,本发明公开了一种制备橙花醇/香叶醇的方法，该方法使用Pt@C催化剂进行非均相催化，将橙花醛/...,万华化学集团股份有限公司,2019-12-11,CN201911274019.4,2021-06-18,CN112979422A,发明申请,有效,...,NaN,1.0,10.0,授权,发明申请,patent202404,万华化学集团股份有限公司,NaN,NaN,NaN

In [12]:
patent_co.columns

Index(['序号', '标题 (中文)', '摘要 (中文)', '申请人', '申请日', '申请号', '首次公开日', '公开（公告）号',
       '专利类型', '专利有效性', '公开国别', 'IPC主分类', 'IPC', '申请人类型', '发明人', '发明人数量',
       '简单同族', '扩展同族', '简单同族个数', '引证专利', '引证科技文献', '引证次数', '被引证次数', '引证申请人',
       '被引证申请人', '申请人数量', '许可次数', '转让次数', '权利要求数量', '当前法律状态', '公开类型',
       'table_name', '工商全称', '中文全称', '股票代码', '首次上市日期'],
      dtype='object')

In [13]:
patent_co[patent_co.股票代码.isna()].filter(like='人')

,申请人,申请人类型,发明人,发明人数量,引证申请人,被引证申请人,申请人数量
713278,万华化学集团股份有限公司,企业,王亚新; 王联防; 张永振; 董菁; 程英; 迟森森; 王文; 曹娜,8.0,巴斯福股份公司; 复旦大学; 上海华谊(集团)上硫化工有限公司; 山东新和成药业有限公司; ...,NaN,1.0
712817,万华化学集团股份有限公司,企业,王亚新; 王联防; 张永振; 董菁; 程英; 迟森森; 王文; 曹娜,8.0,巴斯福股份公司; 复旦大学; 上海华谊(集团)上硫化工有限公司; 山东新和成药业有限公司; ...,无锡威孚环保催化剂有限公司; 四川大学,1.0

In [3]:
import numpy as np
co_listed=pd.read_excel('data\上市公司名录(中国上市公司协会上市公司行业分类).xlsx')
co_stk=pd.read_excel('data/STK_LISTEDCOINFOANL.xlsx',skiprows=[0,2])
co_stk['首次上市日期']=pd.to_datetime(co_stk['首次上市日期'])

C:\Users\Prime\AppData\Roaming\Python\Python39\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [9]:
co_stk.columns

Index(['股票代码', '股票简称', '统计截止日期', '上市公司ID', '证券ID', '行业名称', '行业代码', '行业名称C',
       '行业代码C', '行业名称D', '行业代码D', '注册具体地址', '公司办公地址', '办公地址邮政编码', '董事会秘书',
       '董秘联系电话', '董秘传真', '董秘电子邮箱', '证券事务代表', '统一社会信用代码', '重大变更', '办公地经度',
       '办公地纬度', 'ISIN编码', '中文全称', '法人代表', '公司成立日期', 'ABH股交叉码', '注册资本', '公司网址',
       '经营范围', '注册地经度', '注册地纬度', '电子邮箱', '首次上市日期', '所属省份代码', '所属省份', '所属城市代码',
       '所属城市', '主营业务', '上市状态'],
      dtype='object')

In [10]:
'万华化学集团股份有限公司' in co_stk.中文全称

False

In [4]:
patent_co.dropna(subset='股票代码',inplace=True)
patent_co['股票代码']=patent_co['股票代码'].astype(int)

In [28]:
patent_co.申请日.isna().sum()

3432

In [31]:
#patent_co.loc[patent_co.申请日.isna(),'申请日']=patent_co.loc[patent_co.申请日.isna(),'首次公开日']
patent_co.loc[patent_co.申请日.isna(),'专利有效性'].value_counts()

专利有效性
失效     3431
未确认       1
Name: count, dtype: int64

In [5]:
patent_co.dropna(subset='申请日',inplace=True)

In [6]:
patent_co['申请年']=patent_co['申请日'].dt.year
patent_co['申请月份']=patent_co['申请日'].astype(str).str[:-3]#.dt.strftime('%Y-%m')
base_date = pd.Timestamp('1970-01-01')
patent_co['月份数'] = (patent_co['申请日'].dt.year - base_date.year) * 12 + (patent_co['申请日'].dt.month - base_date.month)
patent_co['周数'] = ((patent_co['申请日'] - base_date).dt.days // 7) + 1 #patent_co['申请日'].apply( lambda x: len(pd.bdate_range(base_date, x)) // 5  )

In [7]:
Trd_month=pd.read_excel('data\\TRD_Mnth.xlsx',skiprows=[0,2])
Trd_month.dtypes,Trd_month.shape

C:\Users\Prime\AppData\Roaming\Python\Python39\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

(证券代码                   int64
 交易月份                  object
 月开盘日期                  int64
 月开盘价                 float64
 月收盘日期                  int64
 月收盘价                 float64
 月个股交易股数                int64
 月个股交易金额              float64
 月个股流通市值              float64
 月个股总市值               float64
 月交易天数                  int64
 考虑现金红利再投资的月个股回报率     float64
 不考虑现金红利再投资的月个股回报率    float64
 市场类型                   int64
 最新股本变动日期              object
 月盘后成交总量              float64
 月盘后成交总额              float64
 dtype: object,
 (810251, 17))

In [9]:
Trd_month['月开盘日期']=pd.to_datetime(Trd_month['交易月份'].str.cat(Trd_month['月开盘日期'].astype(str),sep='-'))#trd_month['交易月份'] + '-' + trd_month['月开盘日期'].astype(str)
Trd_month['月收盘日期']=pd.to_datetime(Trd_month['交易月份'].str.cat(Trd_month['月收盘日期'].astype(str),sep='-'))
Trd_month['交易年']= Trd_month['月开盘日期'].dt.year
Trd_month['月份数'] = (Trd_month['月开盘日期'].dt.year - base_date.year) * 12 + (Trd_month['月开盘日期'].dt.month - base_date.month)
Trd_month.loc[Trd_month['月份数']==300,'交易月份'].unique()

array(['1995-01'], dtype=object)

In [10]:
trd_month = Trd_month.copy()
trd_month = trd_month[(trd_month['市场类型']==1) |(trd_month['市场类型']==4)]
trd_month = trd_month[(trd_month['月收盘价']>2)]
trd_month['Ndaytrd_pre'] = trd_month.groupby('证券代码')['月交易天数'].shift(1)
trd_month = trd_month[(trd_month['Ndaytrd_pre']>=10)]
trd_month['Mretwd_pre'] = trd_month.groupby('证券代码')['考虑现金红利再投资的月个股回报率'].shift(1)
trd_month.sort_values(by=['月开盘日期','月份数','证券代码'],inplace=True)
trd_month.dropna(subset='Mretwd_pre',inplace=True)
trd_month.reset_index(drop=True,inplace=True)
#trd_month=trd_month.drop_duplicates(subset=['交易月份','证券代码'],keep='first')
trd_month

,证券代码,交易月份,月开盘日期,月开盘价,月收盘日期,月收盘价,月个股交易股数,月个股交易金额,月个股流通市值,月个股总市值,...,考虑现金红利再投资的月个股回报率,不考虑现金红利再投资的月个股回报率,市场类型,最新股本变动日期,月盘后成交总量,月盘后成交总额,交易年,月份数,Ndaytrd_pre,Mretwd_pre
0,5,1991-03,1991-03-01,15.51,1991-03-29,13.62,32000,8.930000e+05,581240.31,1225800.00,...,-0.126363,-0.126363,4,1990-12-10,NaN,NaN,1991,254,13.0,-0.029869
1,600602,1991-03,1991-03-01,511.20,1991-03-29,453.00,17756,8.746555e+06,222423.00,906000.00,...,-0.118334,-0.118334,1,1990-12-19,NaN,NaN,1991,254,18.0,0.017426
2,600651,1991-03,1991-03-01,389.30,1991-03-29,363.30,10198,1.845100e+06,11988.90,11988.90,...,-0.062210,-0.062210,1,1990-12-19,NaN,NaN,1991,254,16.0,-0.034637
3,600653,1991-03,1991-03-01,38.50,1991-03-29,36.30,116580,4.399250e+06,12705.00,18150.00,...,-0.052219,-0.052219,1,1990-12-19,NaN,NaN,1991,254,17.0,0.094911
4,600654,1991-03,1991-03-01,435.10,1991-03-29,405.40,2582,1.092263e+06,8513.40,85174.54,...,-0.063525,-0.063525,1,1990-12-19,NaN,NaN,1991,254,17.0,0.088235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611029,605589,2024-07,2024-07-01,20.30,2024-07-31,20.04,183373919,3.625777e+09,12328844.65,16964040.32,...,-0.012321,-0.012321,1,2024-07-24,0.0,0.0,2024,654,19.0,-0.050538
611030,605598,2024-07,2024-07-01,22.20,2024-07-31,19.85,30673170,6.598376e+08,1486305.29,4878352.69,...,-0.101403,-0.101403,1,2024-07-22,0.0,0.0,2024,654,19.0,0.108499
611031,605599,2024-07,2024-07-01,12.78,2024-07-31,11.49,54949980,6.610917e+08,6740927.92,8936666.92,...,-0.097408,-0.097408,1,2022-09-09,0.0,0.0,2024,654,19.0,-0.063062
611032,7,2024-07,2024-07-02,4.99,2024-07-31,5.09,251985238,1.337447e+09,1572545.54,1763420.54,...,0.073840,0.073840,4,2021-12-31,0.0,0.0,2024,654,19.0,-0.053892
611033,603227,2024-07,2024-07-03,6.82,2024-07-31,6.61,200996744,1.370092e+09,6438638.78,7083888.67,...,0.106512,0.106452,1,2024-02-05,0.0,0.0,2024,654,19.0,-0.086892

In [11]:
patent_co_1=patent_co[patent_co.股票代码.isin(trd_month.证券代码)].copy()
patent_co_1.sort_values(by=['申请日','月份数','股票代码'],inplace=True)
patent_co_1.reset_index(drop=True,inplace=True)
patent_co_1.shape

(1566890, 40)

In [51]:
patent_co_1.申请日.min(),trd_month.月份数.max()#219.0 956.0

(Timestamp('1988-04-22 00:00:00'), 654)

df_co_1['观察年'] = df_co_1['融资年份']
df_append = []

for id, group in df_co_1.groupby('公司序号'):
    co_row = group.loc[:, cols].drop_duplicates('公司序号', keep='first')
    i_years = group['融资年份']

    all_years = pd.concat([i_years, group['成立年份']])

    j_mask = patent_co_1['工商全称'].isin(group['工商全称'])
    j_date = patent_co_1.loc[j_mask, '申请日']
    if not j_date.empty:
        all_years = pd.concat([all_years, j_date.dt.year])

    range_years = np.arange(all_years.min(), all_years.max() + 1)
    missing_years = sorted(set(range_years) - set(i_years))

    for year in missing_years:
        co_row_copy = co_row.copy()
        co_row_copy['观察年'] = year
        df_append.append(co_row_copy)

    if len(df_append) % 1000 == 0:
        print(len(df_append),id)

df_invest=pd.concat([df_co_1,pd.concat(df_append)]).sort_index(kind='mergesort')
df_invest.sort_values(by=['公司序号','观察年','融资时间'],inplace=True)
df_invest.reset_index(drop=True,inplace=True)
df_invest['是否融资']=np.where(df_invest['融资年份']==df_invest['观察年'],1,0)
df_invest.shape#22066

In [13]:
#range(月份数)
#co_month=pd.merge(trd_month[['证券代码','月份数']].drop_duplicates(), patent_co[['股票代码','月份数']].drop_duplicates(), left_on=['证券代码','月份数'], right_on=['股票代码','月份数'],suffixes=('_invest', '_patent'),how='outer')
co_month=pd.concat([trd_month[['证券代码','月份数']].drop_duplicates(), patent_co[['股票代码','月份数']].rename(columns={'股票代码':'证券代码'}).drop_duplicates()])
co_month.groupby('证券代码').月份数.agg(['min','max']).describe()

               min          max
count  5549.000000  5549.000000
mean    469.448730   642.777257
std      95.376681    30.713994
min     219.000000   325.000000
25%     395.000000   645.000000
50%     483.000000   654.000000
75%     546.000000   654.000000
max     652.000000   654.000000

In [14]:
co_month_all=co_month.groupby('证券代码').月份数.apply(lambda x:np.arange(x.min(), x.max() + 1)).explode().reset_index()
co_month_all=co_month_all.merge(trd_month,on=['证券代码','月份数'],how='left')
co_month_all['Month_shift'] = co_month_all.groupby(['证券代码'])['月份数'].transform(lambda x:x.fillna(method='ffill').shift(1))
co_month_all['m_type']=np.where(co_month_all['交易月份'].isna(),0,1)
co_month_all

,证券代码,月份数,交易月份,月开盘日期,月开盘价,月收盘日期,月收盘价,月个股交易股数,月个股交易金额,月个股流通市值,...,不考虑现金红利再投资的月个股回报率,市场类型,最新股本变动日期,月盘后成交总量,月盘后成交总额,交易年,Ndaytrd_pre,Mretwd_pre,Month_shift,m_type
0,1,257,1991-06,1991-06-01,38.53,1991-06-28,33.99,30600.0,1094000.0,900735.00,...,-0.113459,4.0,1991-04-03,NaN,NaN,1991.0,24.0,-0.122253,NaN,1
1,1,258,1991-07,1991-07-01,33.65,1991-07-31,29.54,6100.0,194043.0,782810.00,...,-0.130921,4.0,1991-04-03,NaN,NaN,1991.0,23.0,-0.113459,257.0,1
2,1,259,1991-08,1991-08-01,29.39,1991-08-31,15.00,3243100.0,49576242.0,674833.82,...,-0.411587,4.0,1991-08-01,NaN,NaN,1991.0,16.0,-0.130921,258.0,1
3,1,260,1991-09,1991-09-02,15.00,1991-09-28,14.50,7240500.0,102706985.0,652339.35,...,-0.033333,4.0,1991-08-01,NaN,NaN,1991.0,15.0,-0.411588,259.0,1
4,1,261,1991-10,1991-10-03,14.65,1991-10-31,26.90,10591200.0,243877475.0,1210201.97,...,0.855172,4.0,1991-08-01,NaN,NaN,1991.0,24.0,-0.033333,260.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967344,900956,607,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,606.0,0
967345,900956,608,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,607.0,0
967346,900956,609,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,608.0,0
967347,900956,610,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609.0,0
967348,900956,611,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,610.0,0

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
doc_lda_w2v=pd.read_parquet(f'data\\documents_vec_stk_list.parquet')
doc_lda_w2v.shape#1985628

(1968360, 300)

In [33]:
def year_interval(filter_value,cols):
    filter_value_1 = filter_value.dropna(subset = cols) #filter_value.sort_values(by=['apply_date'],ascending=True)
    return (filter_value_1['申请日'].max()-filter_value_1['申请日'].min()).days//365+1

def process_ipc(filter_patent):
    ipcs_patent = filter_patent['IPC'].str.split(';').explode().str.strip().str.extract('(\w+)/')[0].str[:3]
    return 1.0 - (ipcs_patent.value_counts(normalize=True)**2).sum()

def calculate_metrics(filter_value):
    metrics = {}
    
    # 申请号的唯一数量
    metrics['Application_num'] = filter_value['申请号'].nunique()
    
    # 去重后的 IPC 主分类数量
    metrics['IPC主分类_去重'] = filter_value['IPC主分类'].dropna().map(lambda x: x[:3]).nunique()
    
    # IPC 主分类的平均值
    metrics['IPC主分类_平均'] = metrics['IPC主分类_去重'] / year_interval(filter_value, 'IPC主分类')

    # 计算 IPC 的去重数量和平均值
    ipcs = filter_value['IPC'].str.split(';').explode().str.strip()
    metrics['IPC_个数_去重'] = ipcs.nunique()
    metrics['IPC_个数_平均'] = metrics['IPC_个数_去重'] / year_interval(filter_value, 'IPC')

    # 被引证次数和引证数量
    metrics['被引证次数'] = filter_value['被引证次数'].sum()
    metrics['引证数量'] = filter_value['引证次数'].sum()
    
    # 引证专利的去重数量和平均值
    citing = filter_value['引证专利'].str.split(';').explode().str.strip()
    metrics['引证数量_去重'] = citing.nunique()
    metrics['引证数量_平均'] = metrics['引证数量_去重'] / year_interval(filter_value, '引证专利')

    # 简单同族专利相关统计
    metrics['简单同族个数'] = filter_value['简单同族个数'].sum()
    cognate = filter_value['简单同族'].str.split(';').explode().str.strip()
    metrics['简单同族_去重'] = cognate.nunique()
    metrics['简单同族美日欧_比例'] = cognate.str[:2].isin(['US', 'JP', 'EP']).sum() / cognate.shape[0]

    # 发明人数量
    metrics['发明人数量'] = filter_value['发明人数量'].sum()
    metrics['发明人数量_去重'] = filter_value['发明人'].str.split(';').explode().str.strip().nunique()
    metrics['发明人数量_平均'] = metrics['发明人数量_去重'] / year_interval(filter_value, '发明人')

    # 权利要求数量和引证科技文献数量
    metrics['权利要求数量'] = filter_value['权利要求数量'].sum()
    metrics['引证科技文献数量'] = filter_value['引证科技文献'].count()  # 80%空,格式不统一
    
    # 有效专利数量和有效比例
    metrics['有效数量'] = (filter_value['专利有效性'] == '有效').sum()
    metrics['有效_比例'] = metrics['有效数量'] / filter_value.shape[0]

    # 发明授权和发明申请专利数量
    metrics['发明授权'] = (filter_value['专利类型'] == '发明授权').sum()
    metrics['发明申请'] = (filter_value['专利类型'] == '发明申请').sum()

    metrics['实用新型']=(filter_value['专利类型'] == '实用新型').sum()
    metrics['外观设计']=(filter_value['专利类型'] == '外观设计').sum()

    return metrics

In [20]:
patent_co['IPC主分类'].isna().sum(),patent_co.loc[patent_co['IPC主分类'].notna(),'申请日'].min()

(204300, Timestamp('1990-08-24 00:00:00'))

In [57]:
%%time
results = []

for m in range(219,655):#219,655
    co_month_t=co_month_all[co_month_all['月份数'] == m]
    patent_value=patent_co_1[patent_co_1['月份数'] <= m]
    
    group_ids_t=patent_value.groupby('股票代码')['公开（公告）号'].apply(list)
    ids_vec = group_ids_t.apply(lambda x: doc_lda_w2v.loc[doc_lda_w2v.index.isin(x)].mean(axis=0))    #ids_vec.index = group_ids_t['股票代码']
    ids_vec = ids_vec[ids_vec.sum(axis=1) != 0]#使用 lda_w2v 模型将公司的专利文档向量化后的表示
    if not ids_vec.empty:
        cosine_sim=pd.DataFrame(cosine_similarity(ids_vec.values), index=ids_vec.index, columns=ids_vec.index)

    ids_ipc = pd.crosstab(patent_value['股票代码'], patent_value['IPC主分类'].str.strip().str[:3])
    ids_ipc = ids_ipc[ids_ipc.sum(axis=1) != 0] #.reindex(columns=sorted(ipc_base.columns), fill_value=0)
    if not ids_ipc.empty:
        cosine_sim_ipc=pd.DataFrame(cosine_similarity(ids_ipc.values), index=ids_ipc.index, columns=ids_ipc.index)
  
    invest_sorted = co_month_t.dropna(subset='Mretwd_pre').sort_values(by=['证券代码', '月收盘日期']) 
    print(m,co_month_t['交易月份'].dropna().unique(),len(co_month_t),len(invest_sorted),len(group_ids_t),len(ids_vec),len(ids_ipc))
    #-------
    for index,row in co_month_t.iterrows():
        company_id = row['证券代码']
        last_date = row['月收盘日期']
        pre_month = row['Month_shift']

        if company_id in ids_vec.index: #company_id in cosine_sim.index 
            co_month_all.at[index,'listed_tech_closenesss'] = cosine_sim.loc[company_id].mean()
            recent_invest = invest_sorted[(invest_sorted['证券代码'].isin(cosine_sim.columns))&(invest_sorted['月收盘日期'] < last_date)].drop_duplicates(subset=['证券代码'], keep='last')
            if not recent_invest.empty:#recent_invest['Mretwd_pre'] notna
                tech_closeness_scores = cosine_sim.loc[company_id, recent_invest['证券代码']].fillna(0)  # 获取该公司与其他公司的技术相似度 
                weighted_vc_amount = np.dot(tech_closeness_scores.values, recent_invest['Mretwd_pre'].values) / tech_closeness_scores.sum()
                co_month_all.at[index,'tech_closeness_ret'] = weighted_vc_amount

        if company_id in  ids_ipc.index:
            co_month_all.at[index, 'listed_ipc_closenesss'] =  cosine_sim_ipc.loc[company_id].mean()
            recent_invest = invest_sorted[invest_sorted['证券代码'].isin(cosine_sim_ipc.columns)&(invest_sorted['月收盘日期'] < last_date)].drop_duplicates(subset=['证券代码'], keep='last')
            if not recent_invest.empty:
                tech_closeness_scores = cosine_sim_ipc.loc[company_id, recent_invest['证券代码']].fillna(0) 
                tech_closeness_sum = tech_closeness_scores.sum()
                if tech_closeness_sum != 0:
                    weighted_vc_amount = np.dot(tech_closeness_scores.values, recent_invest['Mretwd_pre'].values) / tech_closeness_sum
                    co_month_all.at[index,'ipc_closeness_ret']=weighted_vc_amount
                
         #-------
        filter_patent= patent_value[patent_value['股票代码']==company_id]#t <= m and company_id
        if not filter_patent.empty:
            filter_value = filter_patent if pd.isna(pre_month) else filter_patent[pre_month < filter_patent['月份数']]#trade_pre_t < t <= m and company_id,first:t <= m
            co_month_all.at[index,'知识宽度'] = process_ipc(filter_patent) # 累积量，fillna(method='ffill')
            if not filter_value.empty:
                if filter_value['月份数'].min()==m: # m in filter_value['月份数']
                    co_month_all.at[index,'m_type']|=(1<<1) #标记当期产生专利
            
                metrics = calculate_metrics(filter_value)   # 计算指标
                co_month_all.loc[index, metrics.keys()] = pd.Series(metrics)     # 批量更新
            #-------针对发明授权和发明申请类型的专利进行进一步处理
            mask=(filter_patent['专利类型']=='发明授权') | (filter_patent['专利类型']=='发明申请')
            if mask.sum()>0:
                filter_patent= filter_patent[mask]
                filter_value = filter_patent if pd.isna(pre_month) else filter_patent[pre_month < filter_patent['月份数']]
                metrics = {'知识宽度': process_ipc(filter_patent)}
                if not filter_value.empty:
                    if filter_value['月份数'].min()==m: 
                        metrics['m_type']= row['m_type']|(1<<1) 
                
                    metrics.update(calculate_metrics(filter_value))
                    
                results.append((index,metrics))

219 [] 1 0 1 1 0
220 [] 1 0 1 1 0
221 [] 1 0 1 1 0
222 [] 2 0 2 2 0
223 [] 2 0 2 2 0
224 [] 2 0 2 2 0
225 [] 2 0 2 2 0
226 [] 2 0 2 2 0
227 [] 2 0 2 2 0
228 [] 2 0 2 2 0
229 [] 2 0 2 2 0
230 [] 2 0 2 2 0
231 [] 2 0 2 2 0
232 [] 2 0 2 2 0
233 [] 2 0 2 2 0
234 [] 2 0 2 2 0
235 [] 2 0 2 2 0
236 [] 2 0 2 2 0
237 [] 2 0 2 2 0
238 [] 2 0 2 2 0
239 [] 2 0 2 2 0
240 [] 2 0 2 2 0
241 [] 2 0 2 2 0
242 [] 2 0 2 2 0
243 [] 2 0 2 2 0
244 [] 2 0 2 2 0
245 [] 2 0 2 2 0
246 [] 2 0 2 2 0
247 [] 3 0 3 3 1
248 [] 3 0 3 3 1
249 [] 3 0 3 3 1
250 [] 3 0 3 3 1
251 [] 3 0 3 3 1
252 [] 4 0 4 4 2
253 [] 4 0 4 4 2
254 ['1991-03'] 10 6 4 4 2
255 ['1991-04'] 13 8 4 4 2
256 ['1991-05'] 14 9 4 4 2
257 ['1991-06'] 15 11 4 4 2
258 ['1991-07'] 15 11 4 4 2
259 ['1991-08'] 15 10 4 4 2
260 ['1991-09'] 17 12 4 4 2
261 ['1991-10'] 17 12 4 4 2
262 ['1991-11'] 17 13 4 4 2
263 ['1991-12'] 17 13 4 4 2
264 ['1992-01'] 18 13 5 5 3
265 ['1992-02'] 18 13 5 5 3
266 ['1992-03'] 18 13 5 5 3
267 ['1992-04'] 18 12 5 5 3
268 ['1992-05'] 19 14 5 5 3
269 ['1992-06'] 25 19 6 5 3
270 ['1992-07'] 39 28 11 9 7
271 ['1992-08'] 41 29 11 9 7
272 ['1992-09'] 42 30 11 9 7
273 ['1992-10'] 47 34 12 9 7
274 ['1992-11'] 51 38 12 9 7
275 ['1992-12'] 55 41 13 10 8
276 ['1993-01'] 58 44 13 10 8
277 ['1993-02'] 66 51 14 11 8
278 ['1993-03'] 70 55 14 11 8
279 ['1993-04'] 75 59 15 12 9
280 ['1993-05'] 83 67 15 12 9
281 ['1993-06'] 89 73 15 12 9
282 ['1993-07'] 103 86 16 13 10
283 ['1993-08'] 113 95 17 14 11
284 ['1993-09'] 122 102 19 15 12
285 ['1993-10'] 129 109 19 15 12
286 ['1993-11'] 136 116 19 15 12
287 ['1993-12'] 148 129 19 15 12
288 ['1994-01'] 163 144 21 16 13
289 ['1994-02'] 195 177 21 16 13
290 ['1994-03'] 220 201 22 16 13
291 ['1994-04'] 237 218 22 16 13
292 ['1994-05'] 256 237 23 18 15
293 ['1994-06'] 267 243 23 18 15
294 ['1994-07'] 280 236 24 19 16
295 ['1994-08'] 290 270 25 20 18
296 ['1994-09'] 295 272 28 21 19
297 ['1994-10'] 305 278 30 24 21
298 ['1994-11'] 310 282 32 26 23
299 ['1994-12'] 313 283 33 28 25
300 ['1995-01'] 318 284 36 30 26
301 ['1995-02'] 318 283 36 30 26
302 ['1995-03'] 319 284 37 31 27
303 ['1995-04'] 323 285 39 32 28
304 ['1995-05'] 330 292 42 36 29
305 ['1995-06'] 331 292 42 36 29
306 ['1995-07'] 331 296 42 36 29
307 ['1995-08'] 331 296 42 36 29
308 ['1995-09'] 332 296 42 36 29
309 ['1995-10'] 333 296 43 37 30
310 ['1995-11'] 335 297 46 37 31
311 ['1995-12'] 341 299 49 40 33
312 ['1996-01'] 348 306 49 40 33
313 ['1996-02'] 352 310 49 40 33
314 ['1996-03'] 354 313 49 40 33
315 ['1996-04'] 357 316 49 40 33
316 ['1996-05'] 366 325 52 43 35
317 ['1996-06'] 372 331 55 46 38
318 ['1996-07'] 383 342 55 46 38
319 ['1996-08'] 398 355 57 48 39
320 ['1996-09'] 427 385 58 49 40
321 ['1996-10'] 447 406 58 49 40
322 ['1996-11'] 461 420 58 49 40
323 ['1996-12'] 485 443 62 53 44
324 ['1997-01'] 512 470 63 54 46
325 ['1997-02'] 548 505 65 56 48
326 ['1997-03'] 559 505 66 57 48
327 ['1997-04'] 575 533 67 58 49
328 ['1997-05'] 593 550 69 60 52
329 ['1997-06'] 608 566 69 60 52
330 ['1997-07'] 637 593 73 64 56
331 ['1997-08'] 669 627 74 64 56
332 ['1997-09'] 715 676 77 67 59
333 ['1997-10'] 727 686 81 71 63
334 ['1997-11'] 735 692 83 73 63
335 ['1997-12'] 748 702 87 76 66
336 ['1998-01'] 757 710 89 78 68
337 ['1998-02'] 768 719 92 81 71
338 ['1998-03'] 772 722 94 84 71
339 ['1998-04'] 780 730 95 85 73
340 ['1998-05'] 790 738 97 87 75
341 ['1998-06'] 799 737 99 88 76
342 ['1998-07'] 811 747 100 89 77
343 ['1998-08'] 835 773 105 94 82
344 ['1998-09'] 844 784 107 97 85
345 ['1998-10'] 847 790 108 98 86
346 ['1998-11'] 855 795 112 102 91
347 ['1998-12'] 868 805 118 107 96
348 ['1999-01'] 879 813 123 111 99
349 ['1999-02'] 891 823 127 117 102
350 [] 892 0 132 121 105
351 ['1999-04'] 900 829 136 125 108
352 ['1999-05'] 909 837 140 130 112
353 ['1999-06'] 922 847 151 140 120
354 ['1999-07'] 933 856 156 146 125
355 ['1999-08'] 945 862 164 152 129
356 ['1999-09'] 962 875 171 158 135
357 ['1999-10'] 976 884 178 164 141
358 ['1999-11'] 985 894 181 168 146
359 ['1999-12'] 998 899 193 179 157
360 ['2000-01'] 1009 908 200 187 164
361 ['2000-02'] 1018 918 202 189 166
362 ['2000-03'] 1025 921 209 195 173
363 ['2000-04'] 1029 926 211 197 175
364 ['2000-05'] 1039 932 220 204 183
365 ['2000-06'] 1043 934 223 206 184
366 ['2000-07'] 1058 941 233 213 191
367 ['2000-08'] 1083 958 250 227 203
368 ['2000-09'] 1102 973 256 232 208
369 ['2000-10'] 1134 993 274 252 226
370 ['2000-11'] 1144 997 288 267 241
371 ['2000-12'] 1161 1011 299 277 250
372 ['2001-01'] 1174 1018 307 287 260
373 ['2001-02'] 1190 1033 314 294 267
374 ['2001-03'] 1209 1055 318 298 270
375 ['2001-04'] 1224 1070 330 310 280
376 ['2001-05'] 1238 1083 341 320 290
377 ['2001-06'] 1245 1078 350 330 300
378 ['2001-07'] 1254 1084 358 340 310
379 ['2001-08'] 1266 1093 368 352 320
380 ['2001-09'] 1271 1096 376 359 325
381 ['2001-10'] 1278 1102 383 366 332
382 ['2001-11'] 1286 1111 392 377 342
383 ['2001-12'] 1288 1112 400 385 349
384 ['2002-01'] 1289 1111 404 388 352
385 ['2002-02'] 1295 1116 410 394 358
386 ['2002-03'] 1301 1052 413 398 362
387 ['2002-04'] 1311 1125 432 418 383
388 ['2002-05'] 1316 1116 444 430 396
389 ['2002-06'] 1325 1122 455 441 405
390 ['2002-07'] 1336 1133 469 453 420
391 ['2002-08'] 1344 1143 475 457 424
392 ['2002-09'] 1356 1156 487 470 436
393 ['2002-10'] 1362 1161 491 474 438
394 ['2002-11'] 1370 1171 498 480 445
395 ['2002-12'] 1379 1181 508 489 454
396 ['2003-01'] 1388 1187 517 496 460
397 ['2003-02'] 1392 1193 521 500 464
398 ['2003-03'] 1398 1197 526 505 469
399 ['2003-04'] 1408 1198 536 514 479
400 ['2003-05'] 1412 1189 546 525 490
401 ['2003-06'] 1424 1195 557 536 501
402 ['2003-07'] 1433 1199 571 550 515
403 ['2003-08'] 1444 1207 587 564 527
404 ['2003-09'] 1461 1217 602 580 540
405 ['2003-10'] 1475 1226 615 590 550
406 ['2003-11'] 1484 1234 625 601 561
407 ['2003-12'] 1495 1247 637 613 574
408 ['2004-01'] 1501 1251 640 616 578
409 ['2004-02'] 1507 1253 643 619 582
410 ['2004-03'] 1513 1258 651 627 588
411 ['2004-04'] 1514 1257 655 631 593
412 ['2004-05'] 1520 1248 657 633 595
413 ['2004-06'] 1529 1257 668 645 607
414 ['2004-07'] 1536 1265 678 653 615
415 ['2004-08'] 1540 1271 683 657 620
416 ['2004-09'] 1557 1299 692 666 627
417 ['2004-10'] 1569 1302 703 676 638
418 ['2004-11'] 1581 1315 711 686 648
419 ['2004-12'] 1599 1317 732 706 668
420 ['2005-01'] 1601 1317 734 708 670
421 ['2005-02'] 1604 1325 735 709 671
422 ['2005-03'] 1611 1315 743 717 679
423 ['2005-04'] 1612 1277 748 723 685
424 ['2005-05'] 1618 1262 761 736 699
425 ['2005-06'] 1630 1254 773 748 709
426 ['2005-07'] 1636 1200 778 753 714
427 ['2005-08'] 1642 1278 786 761 721
428 ['2005-09'] 1651 1291 797 774 732
429 ['2005-10'] 1656 1251 804 782 740
430 ['2005-11'] 1677 1136 827 806 765
431 ['2005-12'] 1697 1190 855 834 793
432 ['2006-01'] 1707 1161 864 842 802
433 ['2006-02'] 1712 1121 867 846 806
434 ['2006-03'] 1721 1099 876 855 816
435 ['2006-04'] 1727 1077 887 864 824
436 ['2006-05'] 1733 1103 892 869 829
437 ['2006-06'] 1738 1115 897 874 834
438 ['2006-07'] 1749 1154 910 887 848
439 ['2006-08'] 1762 1157 921 898 859
440 ['2006-09'] 1784 1238 939 916 877
441 ['2006-10'] 1798 1254 946 923 883
442 ['2006-11'] 1817 1261 959 936 895
443 ['2006-12'] 1856 1283 991 965 924
444 ['2007-01'] 1860 1264 1001 975 936
445 ['2007-02'] 1888 1289 1018 990 950
446 ['2007-03'] 1908 1325 1029 1000 958
447 ['2007-04'] 1920 1343 1039 1011 968
448 ['2007-05'] 1930 1327 1044 1016 974
449 ['2007-06'] 1948 1322 1056 1026 983
450 ['2007-07'] 1971 1352 1071 1043 999
451 ['2007-08'] 1986 1366 1081 1054 1010
452 ['2007-09'] 2007 1350 1100 1072 1030
453 ['2007-10'] 2033 1369 1111 1083 1039
454 ['2007-11'] 2061 1371 1128 1100 1056
455 ['2007-12'] 2088 1381 1147 1122 1075
456 ['2008-01'] 2107 1392 1160 1135 1088
457 ['2008-02'] 2133 1410 1169 1144 1095
458 ['2008-03'] 2159 1421 1186 1161 1113
459 ['2008-04'] 2183 1441 1201 1177 1128
460 ['2008-05'] 2203 1438 1211 1187 1139
461 ['2008-06'] 2221 1452 1223 1201 1153
462 ['2008-07'] 2240 1478 1234 1215 1167
463 ['2008-08'] 2263 1503 1246 1227 1180
464 ['2008-09'] 2285 1514 1259 1240 1194
465 ['2008-10'] 2301 1483 1269 1250 1203
466 ['2008-11'] 2319 1512 1282 1263 1216
467 ['2008-12'] 2356 1533 1313 1293 1245
468 ['2009-01'] 2371 1539 1325 1305 1254
469 ['2009-02'] 2391 1556 1339 1319 1268
470 ['2009-03'] 2411 1550 1356 1335 1286
471 ['2009-04'] 2427 1553 1369 1348 1300
472 ['2009-05'] 2447 1533 1379 1357 1311
473 ['2009-06'] 2472 1542 1403 1382 1338
474 ['2009-07'] 2495 1542 1417 1396 1352
475 ['2009-08'] 2515 1538 1432 1411 1368
476 ['2009-09'] 2541 1548 1446 1426 1381
477 ['2009-10'] 2559 1556 1456 1437 1392
478 ['2009-11'] 2583 1569 1470 1452 1408
479 ['2009-12'] 2621 1576 1488 1470 1428
480 ['2010-01'] 2649 1586 1505 1487 1443
481 ['2010-02'] 2667 1606 1516 1498 1454
482 ['2010-03'] 2685 1620 1523 1505 1463
483 ['2010-04'] 2702 1639 1534 1516 1475
484 ['2010-05'] 2727 1654 1548 1530 1488
485 ['2010-06'] 2763 1675 1568 1551 1507
486 ['2010-07'] 2789 1687 1586 1569 1523
487 ['2010-08'] 2825 1704 1603 1586 1541
488 ['2010-09'] 2848 1732 1617 1600 1554
489 ['2010-10'] 2870 1737 1628 1611 1566
490 ['2010-11'] 2893 1759 1640 1623 1574
491 ['2010-12'] 2941 1777 1665 1648 1599
492 ['2011-01'] 2962 1788 1678 1661 1611
493 ['2011-02'] 2981 1817 1684 1667 1617
494 ['2011-03'] 3000 1820 1696 1679 1629
495 ['2011-04'] 3021 1830 1710 1693 1645
496 ['2011-05'] 3045 1855 1719 1702 1655
497 ['2011-06'] 3073 1866 1734 1717 1672
498 ['2011-07'] 3090 1888 1743 1726 1680
499 ['2011-08'] 3120 1899 1759 1743 1697
500 ['2011-09'] 3151 1916 1782 1766 1722
501 ['2011-10'] 3165 1925 1787 1771 1727
502 ['2011-11'] 3189 1925 1804 1788 1740
503 ['2011-12'] 3232 1940 1832 1816 1769
504 ['2012-01'] 3243 1953 1838 1822 1776
505 ['2012-02'] 3262 1957 1844 1828 1783
506 ['2012-03'] 3279 1970 1853 1837 1791
507 ['2012-04'] 3300 1972 1867 1851 1804
508 ['2012-05'] 3322 1981 1876 1860 1812
509 ['2012-06'] 3339 2000 1889 1874 1828
510 ['2012-07'] 3364 2013 1906 1891 1845
511 ['2012-08'] 3392 2032 1919 1904 1858
512 ['2012-09'] 3415 2035 1929 1915 1869
513 ['2012-10'] 3430 2054 1937 1923 1878
514 ['2012-11'] 3448 2062 1945 1931 1887
515 ['2012-12'] 3483 2074 1953 1939 1897
516 ['2013-01'] 3512 2057 1966 1952 1909
517 ['2013-02'] 3518 2066 1971 1957 1915
518 ['2013-03'] 3532 2060 1978 1964 1923
519 ['2013-04'] 3546 2058 1983 1969 1929
520 ['2013-05'] 3572 2052 1988 1974 1934
521 ['2013-06'] 3588 2025 1998 1984 1942
522 ['2013-07'] 3614 2014 2008 1994 1953
523 ['2013-08'] 3628 2033 2017 2003 1963
524 ['2013-09'] 3645 2019 2024 2010 1969
525 ['2013-10'] 3660 2022 2031 2017 1977
526 ['2013-11'] 3676 2016 2037 2023 1983
527 ['2013-12'] 3709 2029 2050 2036 1997
528 ['2014-01'] 3720 2017 2055 2041 2002
529 ['2014-02'] 3730 2012 2062 2048 2008
530 ['2014-03'] 3753 2004 2074 2060 2019
531 ['2014-04'] 3772 2003 2083 2069 2027
532 ['2014-05'] 3791 1976 2096 2082 2038
533 ['2014-06'] 3812 1969 2105 2091 2047
534 ['2014-07'] 3835 1975 2116 2102 2057
535 ['2014-08'] 3848 1985 2124 2110 2063
536 ['2014-09'] 3866 1994 2134 2120 2073
537 ['2014-10'] 3892 1963 2148 2134 2087
538 ['2014-11'] 3916 1971 2157 2143 2095
539 ['2014-12'] 3951 1994 2173 2159 2112
540 ['2015-01'] 3968 1986 2183 2169 2124
541 ['2015-02'] 3980 1969 2185 2171 2126
542 ['2015-03'] 3999 1983 2194 2180 2134
543 ['2015-04'] 4020 1995 2202 2188 2142
544 ['2015-05'] 4036 1963 2211 2197 2153
545 ['2015-06'] 4054 1954 2218 2204 2161
546 ['2015-07'] 4073 1918 2226 2212 2169
547 ['2015-08'] 4099 1877 2231 2217 2175
548 ['2015-09'] 4127 1924 2239 2225 2183
549 ['2015-10'] 4141 1959 2247 2233 2192
550 ['2015-11'] 4169 1985 2259 2245 2203
551 ['2015-12'] 4221 2058 2279 2265 2220
552 ['2016-01'] 4236 2099 2290 2276 2231
553 ['2016-02'] 4248 2104 2296 2282 2237
554 ['2016-03'] 4269 2116 2302 2288 2243
555 ['2016-04'] 4284 2123 2308 2294 2248
556 ['2016-05'] 4304 2108 2317 2303 2257
557 ['2016-06'] 4330 2127 2328 2314 2267
558 ['2016-07'] 4346 2152 2339 2325 2276
559 ['2016-08'] 4378 2184 2352 2338 2289
560 ['2016-09'] 4391 2220 2356 2342 2292
561 ['2016-10'] 4410 2213 2361 2347 2298
562 ['2016-11'] 4432 2242 2371 2357 2310
563 ['2016-12'] 4463 2252 2379 2365 2320
564 ['2017-01'] 4489 2277 2389 2375 2329
565 ['2017-02'] 4500 2280 2391 2377 2331
566 ['2017-03'] 4522 2313 2394 2380 2335
567 ['2017-04'] 4541 2347 2404 2391 2344
568 ['2017-05'] 4557 2351 2408 2395 2350
569 ['2017-06'] 4582 2374 2421 2408 2365
570 ['2017-07'] 4608 2415 2432 2419 2376
571 ['2017-08'] 4626 2420 2438 2425 2382
572 ['2017-09'] 4636 2475 2445 2432 2389
573 ['2017-10'] 4650 2498 2450 2437 2394
574 ['2017-11'] 4672 2530 2460 2447 2404
575 ['2017-12'] 4705 2567 2471 2458 2415
576 ['2018-01'] 4720 2586 2475 2462 2419
577 ['2018-02'] 4724 2592 2479 2466 2424
578 ['2018-03'] 4739 2513 2485 2472 2429
579 ['2018-04'] 4746 2562 2489 2476 2433
580 ['2018-05'] 4752 2581 2493 2480 2438
581 ['2018-06'] 4762 2594 2496 2484 2441
582 ['2018-07'] 4779 2603 2504 2492 2450
583 ['2018-08'] 4794 2658 2510 2498 2456
584 ['2018-09'] 4812 2693 2516 2504 2462
585 ['2018-10'] 4821 2701 2527 2515 2472
586 ['2018-11'] 4832 2745 2533 2521 2478
587 ['2018-12'] 4845 2749 2539 2527 2484
588 ['2019-01'] 4847 2761 2541 2529 2485
589 ['2019-02'] 4851 2799 2544 2532 2489
590 ['2019-03'] 4862 2810 2548 2536 2492
591 ['2019-04'] 4873 2822 2554 2542 2499
592 ['2019-05'] 4873 2792 2559 2547 2506
593 ['2019-06'] 4880 2798 2564 2552 2512
594 ['2019-07'] 4884 2784 2571 2559 2521
595 ['2019-08'] 4888 2791 2573 2561 2523
596 ['2019-09'] 4893 2797 2576 2564 2526
597 ['2019-10'] 4893 2800 2582 2570 2530
598 ['2019-11'] 4895 2808 2588 2576 2535
599 ['2019-12'] 4906 2826 2593 2581 2539
600 ['2020-01'] 4907 2821 2594 2582 2541
601 ['2020-02'] 4908 2815 2596 2584 2543
602 ['2020-03'] 4915 2822 2601 2589 2549
603 ['2020-04'] 4917 2804 2603 2591 2550
604 ['2020-05'] 4917 2788 2607 2595 2553
605 ['2020-06'] 4921 2800 2611 2599 2560
606 ['2020-07'] 4922 2824 2612 2600 2561
607 ['2020-08'] 4924 2847 2615 2603 2564
608 ['2020-09'] 4927 2841 2622 2610 2573
609 ['2020-10'] 4932 2855 2625 2613 2576
610 ['2020-11'] 4935 2885 2629 2617 2578
611 ['2020-12'] 4944 2902 2640 2628 2589
612 ['2021-01'] 5010 2897 2661 2649 2609
613 ['2021-02'] 5028 2923 2669 2657 2616
614 ['2021-03'] 5054 2949 2677 2665 2623
615 ['2021-04'] 5073 2957 2687 2675 2632
616 ['2021-05'] 5080 2982 2691 2679 2636
617 ['2021-06'] 5084 3005 2697 2685 2641
618 ['2021-07'] 5099 3011 2703 2691 2647
619 ['2021-08'] 5104 3043 2707 2695 2651
620 ['2021-09'] 5107 3054 2712 2700 2656
621 ['2021-10'] 5106 3053 2717 2705 2662
622 ['2021-11'] 5107 3063 2725 2713 2669
623 ['2021-12'] 5097 3085 2729 2717 2674
624 ['2022-01'] 5055 3079 2731 2719 2676
625 ['2022-02'] 5043 3075 2732 2720 2677
626 ['2022-03'] 5040 3085 2736 2724 2681
627 ['2022-04'] 4996 3053 2736 2724 2681
628 ['2022-05'] 4954 3048 2742 2730 2687
629 ['2022-06'] 4909 3065 2743 2731 2689
630 ['2022-07'] 4851 3078 2746 2734 2693
631 ['2022-08'] 4807 3084 2748 2736 2694
632 ['2022-09'] 4747 3074 2748 2736 2694
633 ['2022-10'] 4723 3081 2752 2740 2698
634 ['2022-11'] 4718 3114 2753 2741 2699
635 ['2022-12'] 4704 3102 2759 2747 2705
636 ['2023-01'] 4621 3112 2759 2747 2705
637 ['2023-02'] 4610 3118 2759 2747 2705
638 ['2023-03'] 4598 3110 2760 2748 2706
639 ['2023-04'] 4584 3103 2764 2752 2710
640 ['2023-05'] 4535 3094 2767 2755 2713
641 ['2023-06'] 4506 3115 2768 2756 2713
642 ['2023-07'] 4481 3139 2770 2758 2713
643 ['2023-08'] 4388 3135 2772 2760 2717
644 ['2023-09'] 4303 3133 2772 2760 2717
645 ['2023-10'] 4255 3126 2777 2765 2722
646 ['2023-11'] 4087 3129 2780 2768 2725
647 ['2023-12'] 3766 3121 2782 2770 2726
648 ['2024-01'] 3259 3098 2783 2771 2727
649 ['2024-02'] 3184 3099 2783 2771 2727
650 ['2024-03'] 3154 3108 2784 2772 2728
651 ['2024-04'] 3111 3074 2785 2773 2729
652 ['2024-05'] 3081 3059 2785 2773 2729
653 ['2024-06'] 3016 2991 2785 2773 2729
654 ['2024-07'] 3007 3006 2786 2774 2730
CPU times: total: 19h 5min 12s
Wall time: 18h 48min 4s

In [58]:
co_month_all.to_csv('data/stk_list_patent_2407.csv', encoding="utf_8_sig")

In [59]:
co_month_all[co_month_all.Application_num.notna()]

,证券代码,月份数,交易月份,月开盘日期,月开盘价,月收盘日期,月收盘价,月个股交易股数,月个股交易金额,月个股流通市值,...,有效数量,有效_比例,发明授权,发明申请,实用新型,外观设计,tech_closeness_ret,ipc_closeness_ret,listed_tech_closenesss,listed_ipc_closenesss
227,1,484,2010-05,2010-05-04,20.10,2010-05-31,17.51,7.259897e+08,1.332143e+10,5.120124e+07,...,0.0,0.000000,0.0,0.0,0.0,1.0,-0.085109,NaN,0.636899,NaN
259,1,516,2013-01,2013-01-04,16.32,2013-01-31,21.10,1.300848e+09,2.441936e+10,6.552305e+07,...,2.0,0.666667,1.0,2.0,0.0,0.0,0.133719,0.194241,0.740136,0.076379
302,1,559,2016-08,2016-08-01,9.18,2016-08-31,9.49,1.738666e+09,1.627913e+10,1.388499e+08,...,0.0,0.000000,0.0,4.0,0.0,11.0,0.010004,0.021002,0.750928,0.089797
307,1,564,2017-01,2017-01-03,9.11,2017-01-26,9.33,7.629259e+08,7.001209e+09,1.578448e+08,...,8.0,0.800000,4.0,6.0,0.0,0.0,-0.021841,-0.076584,0.744948,0.089306
330,1,587,2018-12,2018-12-03,10.59,2018-12-28,9.38,1.199334e+09,1.197416e+10,1.610569e+08,...,2.0,1.000000,1.0,1.0,0.0,0.0,0.054606,0.062231,0.751670,0.095260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898056,605599,620,NaN,NaT,NaN,NaT,NaN,NaN,NaN,NaN,...,5.0,1.000000,0.0,0.0,0.0,5.0,NaN,NaN,0.634382,NaN
898059,605599,623,2021-12,2021-12-01,12.34,2021-12-31,13.46,1.263676e+08,1.634912e+09,1.046889e+06,...,5.0,1.000000,0.0,0.0,0.0,5.0,0.179828,NaN,0.635510,NaN
898061,605599,625,2022-02,2022-02-07,13.08,2022-02-28,13.15,1.550260e+08,2.010274e+09,1.022778e+06,...,4.0,1.000000,0.0,0.0,0.0,4.0,-0.068149,NaN,0.635497,NaN
898063,605599,627,2022-04,2022-04-01,10.85,2022-04-29,10.34,3.466182e+07,3.651063e+08,8.042224e+05,...,13.0,1.000000,0.0,0.0,0.0,13.0,0.076301,NaN,0.634758,NaN
898066,605599,630,2022-07,2022-07-01,10.83,2022-07-29,10.85,2.438942e+07,2.578524e+08,8.438891e+05,...,1.0,1.000000,0.0,0.0,1.0,0.0,0.127871,0.507317,0.638470,0.028413

In [62]:
co_month_all.shape

(967349, 51)

In [61]:
co_month_all.m_type.value_counts()

m_type
1    511825
0    327940
3     99209
2     28375
Name: count, dtype: int64

In [63]:
res = pd.DataFrame([metrics for _, metrics in results],index=[index for index, _ in results])
res.shape

(441395, 25)

In [66]:
co_month_all.columns,res.columns

(Index(['证券代码', '月份数', '交易月份', '月开盘日期', '月开盘价', '月收盘日期', '月收盘价', '月个股交易股数',
        '月个股交易金额', '月个股流通市值', '月个股总市值', '月交易天数', '考虑现金红利再投资的月个股回报率',
        '不考虑现金红利再投资的月个股回报率', '市场类型', '最新股本变动日期', '月盘后成交总量', '月盘后成交总额', '交易年',
        'Ndaytrd_pre', 'Mretwd_pre', 'Month_shift', 'm_type', 'Application_num',
        'IPC主分类_去重', 'IPC主分类_平均', 'IPC_个数_去重', 'IPC_个数_平均', '知识宽度', '被引证次数',
        '引证数量', '引证数量_去重', '引证数量_平均', '简单同族个数', '简单同族_去重', '简单同族美日欧_比例',
        '发明人数量', '发明人数量_去重', '发明人数量_平均', '权利要求数量', '引证科技文献数量', '有效数量', '有效_比例',
        '发明授权', '发明申请', '实用新型', '外观设计', 'tech_closeness_ret',
        'ipc_closeness_ret', 'listed_tech_closenesss', 'listed_ipc_closenesss'],
       dtype='object'),
 Index(['知识宽度', 'm_type', 'Application_num', 'IPC主分类_去重', 'IPC主分类_平均',
        'IPC_个数_去重', 'IPC_个数_平均', '被引证次数', '引证数量', '引证数量_去重', '引证数量_平均',
        '简单同族个数', '简单同族_去重', '简单同族美日欧_比例', '发明人数量', '发明人数量_去重', '发明人数量_平均',
        '权利要求数量', '引证科技文献数量', '有效数量', '有效_比例', '发明授权', '发明申请', '实用新型', '外观设计'],
       dtype='object'))

In [68]:
trd_month.columns

Index(['证券代码', '交易月份', '月开盘日期', '月开盘价', '月收盘日期', '月收盘价', '月个股交易股数', '月个股交易金额',
       '月个股流通市值', '月个股总市值', '月交易天数', '考虑现金红利再投资的月个股回报率', '不考虑现金红利再投资的月个股回报率',
       '市场类型', '最新股本变动日期', '月盘后成交总量', '月盘后成交总额', '交易年', '月份数', 'Ndaytrd_pre',
       'Mretwd_pre'],
      dtype='object')

In [73]:
cols=list(set(co_month_all.columns)-set(trd_month.columns)-set(res.columns))
cols

['ipc_closeness_ret',
 'tech_closeness_ret',
 'listed_ipc_closenesss',
 'listed_tech_closenesss',
 'Month_shift']

In [84]:
res

,知识宽度,m_type,Application_num,IPC主分类_去重,IPC主分类_平均,IPC_个数_去重,IPC_个数_平均,被引证次数,引证数量,引证数量_去重,...,发明人数量_去重,发明人数量_平均,权利要求数量,引证科技文献数量,有效数量,有效_比例,发明授权,发明申请,实用新型,外观设计
684530,0.500000,2.0,1.0,1.0,1.0,6.0,6.0,1.0,0.0,0.0,...,2.0,2.0,16.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
684531,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684532,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684533,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684534,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897312,0.549600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897480,0.760204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897543,0.898491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897832,0.900564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897927,0.175737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
co_month_all_1=pd.concat([co_month_all[trd_month.columns.to_list()+cols],res],axis=1)
co_month_all_1.shape

(967349, 51)

In [85]:
co_month_all_1.loc[684530]

证券代码                        600679
交易月份                           NaN
月开盘日期                          NaT
月开盘价                           NaN
月收盘日期                          NaT
月收盘价                           NaN
月个股交易股数                        NaN
月个股交易金额                        NaN
月个股流通市值                        NaN
月个股总市值                         NaN
月交易天数                          NaN
考虑现金红利再投资的月个股回报率               NaN
不考虑现金红利再投资的月个股回报率              NaN
市场类型                           NaN
最新股本变动日期                       NaN
月盘后成交总量                        NaN
月盘后成交总额                        NaN
交易年                            NaN
月份数                            247
Ndaytrd_pre                    NaN
Mretwd_pre                     NaN
ipc_closeness_ret              NaN
tech_closeness_ret             NaN
listed_ipc_closenesss          1.0
listed_tech_closenesss    0.791343
Month_shift                    NaN
知识宽度                           0.5
m_type                         2.0
Application_num                1.0
IPC主分类_去重                      1.0
IPC主分类_平均                      1.0
IPC_个数_去重                      6.0
IPC_个数_平均                      6.0
被引证次数                          1.0
引证数量                           0.0
引证数量_去重                        0.0
引证数量_平均                        NaN
简单同族个数                        26.0
简单同族_去重                       26.0
简单同族美日欧_比例                0.192308
发明人数量                          2.0
发明人数量_去重                       2.0
发明人数量_平均                       2.0
权利要求数量                        16.0
引证科技文献数量                       0.0
有效数量                           0.0
有效_比例                          0.0
发明授权                           0.0
发明申请                           1.0
实用新型                           0.0
外观设计                           0.0
Name: 684530, dtype: object

In [87]:
co_month_all_1.m_type.value_counts()

m_type
3.0    72800
2.0    18257
Name: count, dtype: int64

In [88]:
co_month_all_1['m_type'] = np.where(co_month_all_1['m_type'].isna(), 
                                    np.where(co_month_all_1['交易月份'].isna(), 0, 1), 
                                    co_month_all_1['m_type'])
co_month_all_1.m_type.value_counts()

m_type
1.0    538234
0.0    338058
3.0     72800
2.0     18257
Name: count, dtype: int64

In [92]:
co_month_all_1.月收盘日期.max()

Timestamp('2024-07-31 00:00:00')

In [89]:
co_month_all_1.to_csv('data/stk_list_patent_2407_invention.csv')

In [97]:
co_month_all[cols+['知识宽度','Application_num']].describe()

,ipc_closeness_ret,tech_closeness_ret,listed_ipc_closenesss,listed_tech_closenesss,Month_shift,知识宽度,Application_num
count,315121.000000,356969.000000,477773.000000,490022.000000,961800.000000,495602.000000,127584.000000
mean,0.032455,0.028941,0.068867,0.837105,532.097267,0.570893,11.328921
std,0.160907,0.117551,0.036991,0.061773,84.998288,0.286234,48.714029
min,-0.436892,-0.363596,0.000831,0.530057,219.000000,0.000000,1.000000
25%,-0.043211,-0.033607,0.039171,0.809379,479.000000,0.408163,1.000000
50%,0.019231,0.022973,0.067486,0.855214,549.000000,0.643599,3.000000
75%,0.082826,0.076862,0.093041,0.882573,601.000000,0.795000,7.000000
max,3.555497,2.610577,1.000000,1.000000,653.000000,1.000000,2938.000000

In [96]:
co_month_all_1[cols+['知识宽度','Application_num']].describe()

,ipc_closeness_ret,tech_closeness_ret,listed_ipc_closenesss,listed_tech_closenesss,Month_shift,知识宽度,Application_num
count,315121.000000,356969.000000,477773.000000,490022.000000,961800.000000,441395.000000,91057.000000
mean,0.032455,0.028941,0.068867,0.837105,532.097267,0.511352,8.251886
std,0.160907,0.117551,0.036991,0.061773,84.998288,0.283123,39.455837
min,-0.436892,-0.363596,0.000831,0.530057,219.000000,0.000000,1.000000
25%,-0.043211,-0.033607,0.039171,0.809379,479.000000,0.320000,1.000000
50%,0.019231,0.022973,0.067486,0.855214,549.000000,0.575446,2.000000
75%,0.082826,0.076862,0.093041,0.882573,601.000000,0.745845,4.000000
max,3.555497,2.610577,1.000000,1.000000,653.000000,1.000000,2233.000000

In [99]:
co_month_all_1[['发明授权', '发明申请', '实用新型', '外观设计']].describe()

               发明授权          发明申请     实用新型     外观设计
count  91057.000000  91057.000000  91057.0  91057.0
mean       3.506738      6.079214      0.0      0.0
std       19.106575     32.663951      0.0      0.0
min        0.000000      0.000000      0.0      0.0
25%        0.000000      1.000000      0.0      0.0
50%        1.000000      1.000000      0.0      0.0
75%        2.000000      3.000000      0.0      0.0
max     1121.000000   2232.000000      0.0      0.0

In [102]:
import json
json.dumps('')

'""'